mol_resname: ACE
data_dir: ./trainset
gromacs:
  fn_mdp_em:
    - ../01-prepare/train/em.mdp
    - ../01-prepare/train/em.mdp
    - ../01-prepare/train/em.mdp
  fn_mdp_prod:
    - ../01-prepare/train/nvt-000.mdp
    - ../01-prepare/train/nvt-001.mdp
    - ../01-prepare/train/nvt-002.mdp
  fn_coordinates:
    - ../01-prepare/train/system-000.gro
    - ../01-prepare/train/system-001.gro
    - ../01-prepare/train/system-002.gro
  fn_topol:
    - ../01-prepare/train/topol-000.top
    - ../01-prepare/train/topol-001.top
    - ../01-prepare/train/topol-002.top
  fn_ndx:
    - ../01-prepare/train/index-000.ndx
    - ../01-prepare/train/index-001.ndx
    - ../01-prepare/train/index-002.ndx
  n_steps:
    - 100000
    - 100000
    - 100000
bounds:
  charge CC: [0.0, 1.0]
  charge OC: [-0.8, -0.3]
#  charge CT3: [-1.0, 0.3]
  charge HA3: [-0.3, 0.3]
implicit_atoms: 'CC'
total_charge: -0.80
n_samples: 5
compress: false
cleanup: true
store: ['xtc']
python: python3.13
gmx_cmd: gmx
job_scheduler: local
