mol_resname: ACE
data_dir: ./trainset
gromacs:
  fn_mdp_em:
    - ../01-prepare/train/em.mdp
    - ../01-prepare/train/em.mdp
    - ../01-prepare/train/em.mdp
  fn_mdp_prod:
    - ../01-prepare/train/nvt-000.mdp
    - ../01/prepare/train/nvt-001.mdp
    - ../01/prepare/train/nvt-002.mdp
  fn_coordinates:
    - ../01-prepare/train/win-000.gro
    - ../01-prepare/train/win-001.gro
    - ../01-prepare/train/win-002.gro
  fn_topol:
    - ../01-prepare/train/topol-000.top
    - ../01-prepare/train/topol-001.top
    - ../01-prepare/train/topol-002.top
  fn_ndx:
    - ../01-prepare/train/index-000.ndx
    - ../01-prepare/train/index-001.ndx
    - ../01-prepare/train/index-002.ndx
  n_steps:
    - 200000
    - 200000
    - 200000
bounds:
  charge CC: [0.0, 1.0]
  charge OC: [-0.8, -0.3]
  charge CT3: [-1.0, 0.3]
  charge HA3: [-0.3, 0.3]
implicit_atomtype: CC
total_charge: -0.80
n_samples: 10
compress: false
cleanup: true
store: ['xtc']
python: python3.13
gmx_cmd: gmx
job_scheduler: slurm
slurm:
  max_parallel_jobs: 1500
  preamble:
    job-name: ace
    nodes: 1
    ntasks-per-node: 1
    cpus-per-task: 1
    mem: 1G
    time: 00:40:00
    partition: a36_any
  commands:
    - source /uochb/soft/a/spack/20221129-git/share/spack/setup-env.sh
    - spack load gromacs@2022.4 ~mpi
    - export WORKDIR=/dev/shm/$USER/$SLURM_JOB_ID
    - mkdir -p $WORKDIR || exit 1
    - cd $WORKDIR
    - RUN MD
    - rm -rf $WORKDIR
    - sleep 2
    - exit
